# Generated by Django 2.1 on 2018-09-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='nom',
            field=models.CharField(default='nom', max_length=200, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='prenom',
            field=models.CharField(default='prenom', max_length=200, verbose_name='prenom'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=20, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='username for login'),
        ),
    ]
