# Generated by Django 2.1 on 2018-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20180901_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nom',
            field=models.CharField(default='Nom', max_length=200, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='prenom',
            field=models.CharField(default='Prenom', max_length=200, verbose_name='prenom'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
