# Generated by Django 2.1 on 2018-09-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20180901_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nom',
            field=models.CharField(default='Nom', max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='prenom',
            field=models.CharField(default='Prenom', max_length=200, verbose_name='Prenom'),
        ),
    ]
