# Generated by Django 2.1 on 2018-09-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20180901_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name_plural': 'cours'},
        ),
        migrations.AlterModelOptions(
            name='creneau',
            options={'verbose_name_plural': 'crenaux'},
        ),
        migrations.AlterField(
            model_name='cours',
            name='jour',
            field=models.CharField(choices=[('LUN', 'LUNDI'), ('MAR', 'MARDI'), ('MER', 'MERCREDI'), ('JEU', 'JEUDI'), ('VEN', 'VENDREDI'), ('SAM', 'SAMEDI'), ('DIM', 'DIMANCHE')], max_length=20, verbose_name='Jour de la semaine'),
        ),
    ]
