# Generated by Django 2.1 on 2018-09-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20180903_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='duree',
            field=models.IntegerField(default=60, verbose_name='Duree en minutes'),
        ),
    ]
