# Generated by Django 2.1 on 2018-09-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_cours_duree'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together={('jour', 'heure')},
        ),
    ]
