# Generated by Django 2.1 on 2018-09-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20180906_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='credit',
            field=models.IntegerField(default=0, max_length=10, verbose_name='credits'),
        ),
    ]
