# Generated by Django 2.1 on 2018-09-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_myuser_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='credits'),
        ),
    ]
