# Generated by Django 2.1 on 2018-09-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_auto_20180907_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='reservations',
            field=models.IntegerField(default=1, verbose_name='Nombre de reservations'),
        ),
    ]
