# Generated by Django 2.1 on 2018-09-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20180914_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='reservations',
            field=models.IntegerField(default=0, verbose_name='Nombre de reservations'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='credit',
            field=models.IntegerField(default=1, verbose_name='credits'),
        ),
    ]
