# Generated by Django 2.1 on 2018-09-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20180914_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='date',
            field=models.DateTimeField(verbose_name='Date du cours'),
        ),
    ]
