# Generated by Django 2.1 on 2018-09-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_auto_20180914_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='heure',
            field=models.TimeField(verbose_name='Heure du cours'),
        ),
    ]
