# Generated by Django 2.1 on 2018-09-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_reservation_en_attente'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='en_attente',
            field=models.IntegerField(default=0, verbose_name='En attente'),
        ),
    ]
