# Generated by Django 2.1 on 2018-09-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_creneau_en_attente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='en_attente',
            field=models.IntegerField(default=0, verbose_name='en_attente'),
        ),
    ]
