# Generated by Django 2.1 on 2018-09-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_auto_20180921_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='date',
            field=models.DateTimeField(unique=True, verbose_name='Date du cours'),
        ),
    ]
